name: running_services_monitor
description: "Running Services Monitor"
publish_to: 'none'
version: 1.0.8+7

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  appcheck: ^1.5.4+1
  installed_apps: ^2.0.0
  flutter_svg: ^2.0.10+1
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0
  bloc: ^9.1.0
  injectable: ^2.6.0
  get_it: ^9.1.0
  flutter_bloc: ^9.1.1
  hydrated_bloc: ^10.1.1
  path_provider: ^2.1.1
  url_launcher: ^6.2.1
  android_intent_plus: ^6.0.0
  package_info_plus: ^8.1.2
  go_router: ^14.6.2
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  flutter_isolate: ^2.1.0
  flutter_scale_kit: ^1.5.2
  fluttertoast: ^8.2.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.10.4
  freezed: ^3.2.3
  json_serializable: ^6.11.2
  bloc_lint: ^0.3.5
  injectable_generator: ^2.9.1
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.7

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/
