name: running_services_monitor
description: "Running Services Monitor"
publish_to: 'none'
version: 1.0.15+14

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8

  installed_apps: ^2.1.0
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0
  bloc: ^9.1.0
  injectable: ^2.7.1+2
  get_it: ^9.2.0
  flutter_bloc: ^9.1.1
  hydrated_bloc: ^10.1.1
  path_provider: ^2.1.1
  url_launcher: ^6.2.1
  android_intent_plus: ^6.0.0
  package_info_plus: ^9.0.0
  go_router: ^17.0.0
  intl: ^0.20.2
  flutter_scale_kit: ^1.5.2
  fluttertoast: ^9.0.0
  collection: ^1.19.1
  expressive_refresh: ^0.1.2
  loading_indicator_m3e: ^0.1.1
  m3e_design: ^0.2.0
  dynamic_color: ^1.8.1
  progress_indicator_m3e: ^0.1.1
  share_plus: ^12.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.10.4
  build: ^4.0.3
  freezed: ^3.2.3
  json_serializable: ^6.11.2
  bloc_lint: ^0.3.5
  injectable_generator: ^2.9.1
  pigeon: ^26.1.4

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/
